version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
  test:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run: npm ci
      - run: npm test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
